### ISSUE TITLE
fails when narrator is not present in odm file

### ISSUE THREAD

**Issue by bgschiller** [jvolkening/gloc#6]
I have an ODM that is missing the narrator field. When this happens, the program crashes with the following error message:
> undefined value for mandatory argument 'str' encountered at /usr/local/bin/gloc line 1236.

However, I was able to comment out that line and proceed with my download:
```diff
    # update display
    $info_labels{Duration}->set_text( $book->{duration} );
    $info_labels{Title}->set_text(    $book->{title}    );
    $info_labels{Author}->set_text(   $book->{author}   );
-   $info_labels{Narrator}->set_text( $book->{narrator} );
+   #$info_labels{Narrator}->set_text( $book->{narrator} );
    $info_labels{Publisher}->set_text($book->{publisher});
    $info_labels{Expires}->set_text(  $book->{exp_date} );
```

I don't know perl well enough to try making that an optional field, so I hope this helps. Not sure of the legality of sharing fill odm files, but I looked at the XML inside and found that there was only one `<Creator>` tag, with the role of "author". Nothing for Narrator, as I saw in other files that did work.

Thanks for making this! I'm really glad not to have to borrow a computer when I download an audiobook :)

**Comment by jvolkening** [comment]
Thanks for the report. I've never come across this before, but it should be an easy fix. I should be able to simulate the issue, but I might also ask you to test it on your problem file if you're willing.
