### ISSUE TITLE
Handle case when Overdrive inserts unescaped ampersand in CDATA->Metadata->Subjects->Subject

### ISSUE THREAD

**Issue by oliviergt** [jvolkening/gloc#7]
I downloaded a file from overdrive with the following raw text:

```
<?xml version="1.0"?>
<OverDriveMedia ...>
  <License>...</License>
  <![CDATA[<Metadata> ... <Subjects> ... <Subject id="74">Religion & Spirituality</Subject> ...	
```

The CDATA section contains an unescaped ampersand in the subject tag, causing a parsing exception in `gloc`, which is visible in the terminal:

```
*** unhandled exception in callback:
***   
***   not well-formed (invalid token) at line 1, column 770, byte 770 at /usr/lib/x86_64-linux-gnu/perl5/5.30/XML/Parser.pm line 187.
***   XML::Simple called at /usr/local/bin/gloc line 1029.
***  ignoring at /usr/share/perl5/Gtk3.pm line 572.
```

A quick workaround was to remove the & in "Religion & Spirituality", after which `gloc` downloaded the audiobook just fine. Note that  "column 770" is counted from the beginning of the CDATA section, not from the beginning of the file.

In addition, the unhandled exception makes `gloc` unable to open other `.odm` files and the "open audiobook descriptor file" dialogue cannot be closed. You can still close `gloc` through the main window.

I hope this is helpful to others.

**Comment by jvolkening** [comment]
Thanks for the report. Would you be able to share the full original ODM file? This case *should* be handled in the code already but clearly it is not. I have a suspicion but would like to confirm this with the original input.

In any case, an invalid metadata block should trigger a useful error dialog and not freeze the GUI...I will work on this.

**Comment by oliviergt** [comment]
Thank you for the prompt answer. To reproduce the UI issue (error not displayed in the UI and broken dialogue box), you can create an `.odm` file with an intentionally unclosed tag, such as:

```
<?xml version="1.0"?>
<OverDriveMedia id="x" ODMVersion="3.0.0.0" OMCVersion="3.0.0.0">
```

The exception in the terminal is:

```
*** unhandled exception in callback:
***   
***   no element found at line 3, column 0, byte 90 at /usr/lib/x86_64-linux-gnu/perl5/5.30/XML/Parser.pm line 187.
***   XML::Simple called at /usr/local/bin/gloc line 1008.
***  ignoring at /usr/share/perl5/Gtk3.pm line 572.
```

For the parsing error, I searched overdrive for audiobooks in the subjects that have an ampersand, such as "Biography & Autobiography" or "Religion & Spirituality" and downloaded 4 `.odm` files. Gloc parsed two of them just fine, but the remaining two triggered the exception at line 1029. Upon further inspection, the first two files had single ampersand characters whereas the two bad files had multiple &s:

- Bad file A had an & in CDATA->Metadata->Title and an & in CDATA->Metadata->Subjects->Subject (this is the file in the first comment above)
- Bad file B had two different CDATA->Metadata->Subjects->Subject with & in them: <Subject id="23">Family & Relationships</Subject> ... <Subject id="74">Religion & Spirituality</Subject>.

So I believe that around line 1028 `gloc` should read

```
$content =~ s/&/&amp;/g;  # replace all instances of &
```

instead of

```
$content =~ s/&/&amp;/;  # replace first instance of &
```

Thank you again!

**Comment by jvolkening** [comment]
> the first two files had single ampersand characters whereas the two bad files had multiple &s:

Thanks for investigating -- yes, that was my hunch. It should always have been a global regex. There will be a new release shortly with the bugfix and additional graceful error handling for invalid XML files.

**Comment by oliviergt** [comment]
Thank you. I verified that the latest version can open the two "bad" files from overdrive, and gloc now displays parsing exceptions in the UI, bringing me back to the main screen when I dismiss the error box.
